### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by DNXEMPIRE-1** [Huniko-Team/community#158]
### Name

Dennis Nzioki

### Additional Context

I appreciate the commitment to open-source development. Your organization’s projects provide valuable resources and tools that benefit the broader developer community. Contributing to these projects aligns with my passion for open-source and collaborative development.

**Comment by Huniko519** [comment]
<h1><b>Welcome to Huniko Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [Huniko Team](https://github.com/Huniko-Team) </a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
