### ISSUE TITLE
Please invite me to the organization

### ISSUE THREAD

**Issue by SoftwareArchitect9817** [Huniko-Team/community#19]
Please invite me to the organization
I hope to join this organization and contribute my projects

**Comment by cutesquirrel519** [comment]
You've invited Derek Jones to Huniko-Team! They'll be receiving an email shortly. They can also visit _https://github.com/Huniko-Team_ to accept the invitation.

**Comment by cutesquirrel519** [comment]
<h1><b>Welcome to Huniko Team! 🎉</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ Github  <br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
