### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by KTorresgit** [Huniko-Team/community#235]
### Name

Kim Dave Torres

### Additional Context

I recently came across your open-source community on GitHub and was impressed by your commitment to collaborative learning and building innovative projects. Your focus on fostering a supportive environment where developers can grow and share knowledge aligns with my personal values and professional aspirations.

Given my experience and enthusiasm for contributing to open-source projects, I be thrilled to join your team. I believe that my skills in HTML/CSS, JS, PHP, C#, C would be a valuable addition to your ongoing and future projects.

I would appreciate the opportunity to be a part of this dynamic team and contribute to our shared goals.

Thank you for considering my request.

Best regards,
Kim Dave Torres

**Comment by Huniko519** [comment]
<h1><b>Welcome to Huniko Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [Huniko Team](https://github.com/Huniko-Team) </a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
