### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by Shiva-Bajpai** [Huniko-Team/community#260]
### Name

Shiva Bajpai

### Additional Context

I'm Shiva, a passionate developer and sophomore engineering student with a keen interest in web development and software engineering. I have experience working with technologies like JavaScript, React, Next.js, and C++, and I'm always eager to learn and collaborate on exciting projects. I want to be a part of your organization and contribute to the community while sharing knowledge with fellow developers. Let's build something amazing together!

**Comment by Huniko519** [comment]
<h1><b>Welcome to Huniko Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [Huniko Team](https://github.com/Huniko-Team) </a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
