### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by idimetrix** [Huniko-Team/community#275]
### Name

Dmitry Selikhov

### Additional Context

I'm open source advocate and love to do open source contributions:

🚀CTO, 🏗️Software Architect, 🧑‍💻Technical Lead, 👨‍💼3X Founder. 🔗Linking companies with top tech talents.

CV: [https://dmitrii-selikhov.vercel.app](https://dmitrii-selikhov.vercel.app)
GitHub: [https://github.com/idimetrix](https://github.com/idimetrix)
LinkedIn: [https://www.linkedin.com/in/dimetrix](https://www.linkedin.com/in/dimetrix)

**Comment by Huniko519** [comment]
<h1><b>Welcome to Huniko Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [Huniko Team](https://github.com/Huniko-Team) </a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
