### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by izam-mohammed** [Huniko-Team/community#54]
### Name

Izam Mohammed

### Additional Context

I discovered the Huniko-team through recommendations from my colleagues who are already members. What I appreciate most about the team is the strong sense of support and collaboration within the group. I am eager to join the Huniko-team to connect with like-minded individuals who share my passion for the Huniko project and to learn new skills and techniques from the experienced team members.

**Comment by cutesquirrel519** [comment]
<h1><b>Welcome to Huniko Team! 🎉</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ Huniko Team<br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
