### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by eltonninja** [Huniko-Team/community#76]
### Name

Elton Alcantara

### Additional Context

I am particularly interested in collaborating with like-minded individuals who are passionate about creating sustainable technology solutions. I am confident that I can contribute my skills and knowledge to support the development of the Huniko Team. I look forward to the opportunity to work with you and learn from your expertise.

Thank you for considering my application.
Sincerely,
Elton Alcantara

**Comment by Huniko519** [comment]
<h1><b>Welcome to Huniko Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [Huniko Team](https://github.com/Huniko-Team) </a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
