### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by MetaFomos** [Huniko-Team/community#80]
### Name

James

### Additional Context

From the last year, I am getting so much interested in involving open source projects.
Working for the community and open source teams,  can be said as my happiness.
Please allow me to come in Huniko team.
Regards.

**Comment by Huniko519** [comment]
<h1><b>Welcome to Huniko Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [Huniko Team](https://github.com/Huniko-Team) </a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
