### ISSUE TITLE
Please invite me to the Huniko team

### ISSUE THREAD

**Issue by thunderbolt990525** [Huniko-Team/community#89]
### Name

Harry Dian

### Additional Context

This team is really brilliant!✨
My goal is to be a hard-working, dedicated developer for those who care, support, and hire me.
I all really love what I do, and I believe in my goals.
Of course, there are talented, brilliant engineers everywhere.
However, as in life, there is no success without competition, and I hope that the difficult times of now will be cherished in the future.
“I wanna build a professional career I love while living a life I love while constantly developing new skills.”
This is my creed.
I am always going to try to innovate to avoid obsoletion and make appropriate return for a favor.
Please invite me to the Huniko team~🙌

**Comment by Huniko519** [comment]
<h1><b>Welcome to Huniko Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [Huniko Team](https://github.com/Huniko-Team) </a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈
